# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790de2501698620fbc4eed7798ed60777e0756617c6bb912cff640a5e7b1926026dd80c40bc84a246ff2c7257932dadf24bff39e6a121fb63f51430390fd62a3

test:
  secret_key_base: 5a27f7e7d57b13269a8126fd262b55123e4ce45e8a15a3c97dda1bf603e9c4bd86e4cc896c2ccb74c68056ebee470367f75f66dd4da458cd25edccbc696f3e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
