# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a50ecd897436cc8d61717a2dda11a1a06c2b1e84ab3917bcaa34e26497e4122022e1b9c1b8f9e7f3e724735b0bf919214aece907ad3faf69b8048fa22d8e97b2

test:
  secret_key_base: caa871829291f0f83e9b9534c3c244c4576e9819e24a5d927507c1223ab4adecb264b40fff6d931a0c90f261b644156a9ab8fda3bba572037fa88d4b3a103ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
